### ISSUE TITLE
Unable to find the requested Boost libraries

### ISSUE THREAD

**Issue by ddzyan** [CryptoLions/EOS-MainNet#4]
run ./eosio_build.sh
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /root/opt/boost/include

  The following Boost libraries could not be found:

          boost_system
          boost_chrono
          boost_program_options
          boost_unit_test_framework

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:22 (find_package)

-- Configuring AppBase on Linux
-- Git commit revision: db570801
-- Git commit revision: db570801
-- Git commit revision: db570801
-- Configuring incomplete, errors occurred!
See also "/home/eos-sources/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/eos-sources/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

**Comment by ansigroup** [comment]
what OS do you use?

**Comment by ddzyan** [comment]
centos 7

**Comment by ansigroup** [comment]
Something wrong on boost building. You can make issue on off page (https://github.com/EOSIO/eos), here are only tools how to connect. It works ok under ubuntu ;)
