### ISSUE TITLE
Unable to run nodeos

### ISSUE THREAD

**Issue by pinkhoodie** [CryptoLions/EOS-MainNet#6]
I built eos by following instructions here. But now I can't run ./start.sh and I can't run nodeos. 

When I attempt nodeos, I get: 

`3214892ms thread-0   chain_plugin.cpp:206          plugin_initialize    ] initializing chain plugin
Failed to initialize`

**Comment by ansigroup** [comment]
try to restart with parametrs:
./start.sh --delete-all-blocks --genesis-json genesis.json
