### ISSUE TITLE
cant start the nodes...

### ISSUE THREAD

**Issue by blockchain-expert** [CryptoLions/EOS-MainNet#7]
/start.sh: line 15: /opt/EOSmainNet/stop.sh: No such file or directory
Starting Nodeos 

./start.sh: line 18: /opt/EOSmainNet/nodeos.pid: No such file or directory
./start.sh: line 18: /opt/EOSmainNet/stdout.txt: No such file or directory

**Comment by ansigroup** [comment]
please check you path to sources in start.sh
