### ISSUE TITLE
created producer keypair: private-key = YOUR_BLOCK_SIGN_PUB_KEY=KEY:YOUR_BLOCK_SIGN_PRIV_KEY

### ISSUE THREAD

**Issue by ChristianGrieger** [CryptoLions/EOS-MainNet#9]
Could you explain this please? 

created producer keypair: private-key = YOUR_BLOCK_SIGN_PUB_KEY=KEY:YOUR_BLOCK_SIGN_PRIV_KEY

maybe with a example and how to get it?

And where is the value to see the network we connect to? So its fixed yours?

**Comment by ansigroup** [comment]
cleos create key

YOUR_BLOCK_SIGN_PUB_KEY  - replace with created public key (for example: EOSAAAAA)
YOUR_BLOCK_SIGN_PRIV_KEY  - replace with created private key (for example: 528972937)

private-key = YOUR_BLOCK_SIGN_PUB_KEY=KEY:YOUR_BLOCK_SIGN_PRIV_KEY

private-key = EOSAAAAA=KEY:528972937
